(function () {
  'use strict';

  angular.module('tdpharmaClientApp')
      .config(angularTranslateConfig);

  angularTranslateConfig.$inject = ['$translateProvider'];

  function angularTranslateConfig($translateProvider) {
    $translateProvider.translations('en', {
      GREETING: 'Allo, Allo!',
      LEADING_GREETING: 'Kick-start your pharmacy with tdPharma',
      HOME: 'Home',
      INVENTORY: 'Inventory',
      ORDERS: 'Orders',
      CHECKOUT: 'Checkout',
      SIGNUP: 'Sign up',
      REGISTER: 'Register',
      LOGIN: 'Login',
      LOGOUT: 'Log out',      
      EMAIL: 'Email',
      PASSWORD: 'Password',
      LOGIN_FORM_USER_PASSWORD_ERR: 'Please enter your email and password.',
      PASSWORD_CHANGE_TITLE: 'Change password',
      CURRENT_PASSWORD: 'Current Password',
      NEW_PASSWORD: 'New Password',
      SAVE_CHANGES: 'Save Changes',
      PASSWORD_LENGTH_REQUIREMENT: 'Password must be at least 8 characters.',
      TOASTR_CONGRATS: 'Congratulation!',
      TOASTR_SORRY: 'Sorry!',
      TOASTR_CREATED: ' created!',
      PASSWORD_CHANGE_SUCCESS: 'Your password has been changed successfully',
      INCORRECT_PASSWORD: 'Incorrect Password',
      NEXT: 'Next',
      DRAG_IMAGE: 'Drag image into the gray area to save',
      // Category related pages
      SELECT_A_CATEGORY: 'Select a category',
      'Baby & Kids': 'Baby & Kids',
      'Beauty & Skincare': 'Beauty & Skincare',
      'Personal Care': 'Personal Care',
      'Diet & Fitness': 'Diet & Fitness',
      'Medicine & Health': 'Medicine & Health',
      'Vitamin & Supplement': 'Vitamin & Supplement',
      'Diapering & Potty': 'Diapering & Potty',
      'Bath & Skincare' : 'Bath & Skincare',
      'Formula & Baby Food': 'Formula & Baby Food',
      'Feeding & Mealtime': 'Feeding & Mealtime',
      'Baby Gear': 'Baby Gear',
      "Children's Medicine & Health": "Children's Medicine & Health",
      'Bath & Body': 'Bath & Body',
      'Eye Cosmetics': 'Eye Cosmetics',
      'Foundation, Blush & Bronzer': 'Foundation, Blush & Bronze',
      'Lipsticks & Lip Balm': 'Lipsticks & Lip Balm',
      'Sun Care': 'Sun Care',
      'Skincare Oils & Supplements': 'Skincare Oils & Supplements',
      'Facial Skincare': 'Facial Skincare',
      'Hair Care': 'Hair Care',
      'Oral Care': 'Oral Care',
      'Eye Care': 'Eye Care',
      'Feminine Care': 'Feminine Care',
      'Antiperspirant & Deodorant': 'Antiperspirant & Deodorant',
      'Bladder Protection & Incontinence': 'Bladder Protection & Incontinence',
      'Cotton Balls & Swabs': 'Cotton Balls & Swabs',
      'Wipes & Hand Sanitizers': 'Wipes & Hand Sanitizers',
      'Family Planning': 'Family Planning',
      'Nutrition': 'Nutrition',
      'Weight Management': 'Weight Management',
      'Sports Supplements': 'Sports Supplements',
      'Supplements': 'Supplements',
      'Digestion': 'Digestion',
      'Pain & Fever': 'Pain & Fever',
      'First Aid': 'First Aid',
      'Cough, Cold & Flu': 'Cough, Cold & Flu',
      'Allergy & Sinus': 'Allergy & Sinus',
      'Hemorrhoid & Piles Treatment': 'Hemorrhoid & Piles Treatment',
      'Diabetes': 'Diabetes',
      'Sleeping': 'Sleeping',
      "Women's Health": "Women's Health",
      'Multivitamins': 'Multivitamins',
      'Calcium & Minerals': 'Calcium & Minerals',
      'Fish Oils & Omegas': 'Fish Oils & Omegas',
      'Enzymes': 'Enzymes',
      'Bee Supplements': 'Bee Supplements',
      'Vitamin': 'Vitamin',
      "Greens & Antioxidants": "Greens & Antioxidants",
      'Mushrooms': 'Mushrooms'
    });
    $translateProvider.preferredLanguage('vn');
  }

})();
